name: Build TabletDriverCleanup

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

jobs:
  windowsbuild:
    runs-on: windows-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0'
          include-prerelease: True
      - name: Build
        run: dotnet publish ./src/TabletDriverCleanup /p:PublishSingleFile=true /p:PublishTrimmed=true /p:DebugType=embedded --configuration=Release --self-contained=true -o bin
      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: TabletDriverCleanup
          path: bin