name: Build TabletDriverCleanup

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  windowsbuild:
    runs-on: windows-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0'
      - name: Build
        run: ./build.ps1
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: TabletDriverCleanup
          path: build